server.port=8084
spring.application.name=notification-service


# Database Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/ecommerce_notification
spring.datasource.username=postgres
spring.datasource.password=priyanka

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


# Kafka
spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.use.type.headers=false
#spring.kafka.consumer.properties.spring.json.value.default.type=com.ecommerce.notificationservice.event.PaymentCompletedEvent
spring.kafka.consumer.properties.spring.json.value.default.type=com.ecommerce.notificationservice.event.OrderConfirmedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=960ae54945607b
spring.mail.password=40ccc02dc1412a

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true