server.port=8080
spring.application.name=api-gateway


spring.cloud.gateway.mvc.routes[0].id=order-service
spring.cloud.gateway.mvc.routes[0].uri=http://order-service:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/orders/**

#spring.cloud.gateway.mvc.routes[1].id=inventory-service
#spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8082
#spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/inventory/**
#
#spring.cloud.gateway.mvc.routes[2].id=email-service
#spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8084
#spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/email/**



management.endpoints.web.exposure.include=*
